CRITICAL:  # All the fields under CRITICAL will be required for dandi validate to pass
  - check_subject_exists
  - check_subject_id_exists
  - check_subject_sex
  - check_subject_species_exists
  - check_subject_species_latin_binomial
  - check_subject_age
  - check_subject_proper_age_range
BEST_PRACTICE_VIOLATION:
  - check_data_orientation  # not 100% accurate, so need to deelevate from CRITICAL to skip it in dandi validate
