name: Test against latest DANDI release
on: workflow_call

jobs:
  build-and-test:
    name: Testing against current DANDI release and dev branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: conda-forge
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Install virtualenv
        run: pip install virtualenv

      - name: Install and test against latest DANDI release
        run: |
          virtualenv --system-site-packages --python=python3 venvs/dev3
          source venvs/dev3/bin/activate
          git clone https://github.com/NeurodataWithoutBorders/nwbinspector
          cd nwbinspector
          pip install -e .
          cd ..
          git clone https://github.com/dandi/dandi-cli
          cd dandi-cli
          pip install dandi[test]
          pytest -vv
