name: Test against DANDI dev branch
on: workflow_call

jobs:
  build-and-test:
    name: Testing against current DANDI release and dev branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: conda-forge
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Temporary - testing fix against lower threshold...
        run: |
          pip install virtualenv
          git clone https://github.com/NeurodataWithoutBorders/nwbinspector
          git clone https://github.com/dandi/dandi-cli
          cd dandi-cli
          # Test against a specific branch or commit if needed
          # git checkout a50c4fe243f9a3b72fbcecaea095943be02616d6  # error_fix branch with iteration issue
          virtualenv --system-site-packages --python=python3 venvs/dev3
          source venvs/dev3/bin/activate
          pip install -e .[test]
          cd ../nwbinspector
          # Test against a specific branch or commit if needed
          # git checkout add_downstream_ci
          pip install -e .
          cd ../dandi-cli
          pytest -vv
